// Module registry. Each module defines its schema (fields) plus seed data.
// The generic router in routes.js turns every module into a full CRUD +
// CSV-export + searchable API automatically.

const F = (key, label, type, extra = {}) => ({ key, label, type, ...extra });

const LABS = ['GIA', 'IGI', 'HRD', 'SGL', 'AGS', 'None'];
const SHAPES = ['Round', 'Pear', 'Oval', 'Emerald', 'Princess', 'Marquise', 'Asscher', 'Cushion', 'Radiant', 'Heart'];
const CLARITIES = ['IF', 'VVS1', 'VVS2', 'VS1', 'VS2', 'SI1', 'SI2', 'I1', 'I2'];
const COLORS = ['D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L'];
const GRADES = ['Excellent', 'Very Good', 'Good', 'Fair', 'Poor'];
const FLUORESCENCE = ['None', 'Faint', 'Medium', 'Strong', 'Very Strong'];
const INTENSITIES = ['None', 'Fancy Light', 'Fancy', 'Fancy Intense', 'Fancy Deep', 'Fancy Vivid', 'Fancy Dark'];

const MODULES = [
  {
    key: 'diamonds',
    name: 'Diamonds',
    icon: 'gem',
    group: 'Inventory',
    description: 'Fancy & white diamond stock with full grading certificates.',
    fields: [
      F('stockNo', 'Stock No', 'text', { required: true, searchable: true }),
      F('certificate', 'Certificate', 'text', { searchable: true, placeholder: 'GIA 1234567890' }),
      F('lab', 'Lab', 'select', { options: LABS }),
      F('shape', 'Shape', 'select', { options: SHAPES, searchable: true }),
      F('carat', 'Carat (ct)', 'number', { step: '0.01' }),
      F('color', 'Color', 'select', { options: COLORS }),
      F('clarity', 'Clarity', 'select', { options: CLARITIES }),
      F('cut', 'Cut', 'select', { options: GRADES }),
      F('polish', 'Polish', 'select', { options: GRADES }),
      F('symmetry', 'Symmetry', 'select', { options: GRADES }),
      F('fluorescence', 'Fluorescence', 'select', { options: FLUORESCENCE }),
      F('intensity', 'Intensity', 'select', { options: INTENSITIES }),
      F('modifier', 'Colour Modifier', 'text', { placeholder: 'Pink, Blue, Yellow' }),
      F('measurements', 'Measurements (mm)', 'text', { placeholder: '6.45 x 6.42 x 4.02' }),
      F('depth', 'Depth %', 'number', { step: '0.1' }),
      F('table', 'Table %', 'number', { step: '0.1' }),
      F('price', 'Price (USD)', 'number', { step: '0.01' }),
      F('pricePerCarat', 'Price / Carat', 'number', { step: '0.01' }),
      F('status', 'Status', 'select', { options: ['Available', 'On Memo', 'Reserved', 'Sold', 'Returned'] }),
      F('location', 'Location', 'text', { placeholder: 'Vault A-12' }),
      F('notes', 'Notes', 'textarea'),
    ],
    seed: [
      { stockNo: 'CD-1001', certificate: 'GIA 2201234567', lab: 'GIA', shape: 'Round', carat: 1.52, color: 'F', clarity: 'VVS1', cut: 'Excellent', polish: 'Excellent', symmetry: 'Excellent', fluorescence: 'None', intensity: 'None', modifier: '', measurements: '7.45 x 7.42 x 4.52', depth: 60.9, table: 57, price: 17250, pricePerCarat: 11349, status: 'Available', location: 'Vault A-01', notes: 'Hearts & arrows stone.' },
      { stockNo: 'CD-1002', certificate: 'IGI 4482110033', lab: 'IGI', shape: 'Pear', carat: 2.04, color: 'D', clarity: 'VS2', cut: 'Very Good', polish: 'Excellent', symmetry: 'Very Good', fluorescence: 'Faint', intensity: 'None', modifier: '', measurements: '11.62 x 7.11 x 4.22', depth: 59.3, table: 55, price: 21800, pricePerCarat: 10686, status: 'Available', location: 'Vault A-02', notes: '' },
      { stockNo: 'CD-1003', certificate: 'GIA 2209988776', lab: 'GIA', shape: 'Cushion', carat: 1.85, color: 'G', clarity: 'SI1', cut: 'Very Good', polish: 'Very Good', symmetry: 'Good', fluorescence: 'Medium', intensity: 'None', modifier: '', measurements: '7.25 x 6.9 x 4.6', depth: 64.2, table: 61, price: 9450, pricePerCarat: 5108, status: 'On Memo', location: 'Memo-0041', notes: 'Out to R. Mehta' },
      { stockNo: 'CD-1004', certificate: 'GIA 5198122330', lab: 'GIA', shape: 'Oval', carat: 1.26, color: 'H', clarity: 'VS1', cut: 'Excellent', polish: 'Excellent', symmetry: 'Very Good', fluorescence: 'None', intensity: 'None', modifier: '', measurements: '8.1 x 5.75 x 3.6', depth: 62.3, table: 58, price: 6680, pricePerCarat: 5302, status: 'Available', location: 'Vault A-03', notes: '' },
      { stockNo: 'CD-1005', certificate: 'SGL 2004419018', lab: 'SGL', shape: 'Emerald', carat: 2.31, color: 'E', clarity: 'VVS2', cut: 'Excellent', polish: 'Excellent', symmetry: 'Excellent', fluorescence: 'Faint', intensity: 'None', modifier: '', measurements: '8.5 x 6.35 x 4.8', depth: 61.8, table: 60, price: 26300, pricePerCarat: 11385, status: 'Reserved', location: 'Vault A-04', notes: 'Reserved for A. Kapoor' },
      { stockNo: 'CD-1006', certificate: 'IGI 7766554432', lab: 'IGI', shape: 'Round', carat: 3.02, color: 'I', clarity: 'SI2', cut: 'Good', polish: 'Good', symmetry: 'Fair', fluorescence: 'Strong', intensity: 'None', modifier: '', measurements: '9.32 x 9.3 x 5.75', depth: 61.7, table: 59, price: 19800, pricePerCarat: 6556, status: 'Available', location: 'Vault B-01', notes: 'Strong blue fluorescence.' },
      { stockNo: 'CD-1007', certificate: 'GIA 1199553344', lab: 'GIA', shape: 'Radiant', carat: 2.87, color: 'D', clarity: 'VS1', cut: 'Very Good', polish: 'Excellent', symmetry: 'Very Good', fluorescence: 'None', intensity: 'None', modifier: '', measurements: '8.7 x 7.15 x 5.05', depth: 64.0, table: 62, price: 41200, pricePerCarat: 14355, status: 'Available', location: 'Vault B-02', notes: '' },
      { stockNo: 'CD-1008', certificate: 'HRD 1612340508', lab: 'HRD', shape: 'Princess', carat: 1.11, color: 'G', clarity: 'VS2', cut: 'Very Good', polish: 'Very Good', symmetry: 'Very Good', fluorescence: 'Faint', intensity: 'None', modifier: '', measurements: '6.1 x 6.08 x 4.05', depth: 66.4, table: 70, price: 5120, pricePerCarat: 4613, status: 'Sold', location: 'Sold', notes: 'Sold to Elegant Jewels - invoiced.' },
      { stockNo: 'CD-1009', certificate: 'GIA 2468135790', lab: 'GIA', shape: 'Round', carat: 1.04, color: 'E', clarity: 'VVS1', cut: 'Excellent', polish: 'Excellent', symmetry: 'Excellent', fluorescence: 'None', intensity: 'None', modifier: '', measurements: '6.45 x 6.42 x 3.95', depth: 61.4, table: 57, price: 11200, pricePerCarat: 10769, status: 'Available', location: 'Vault B-03', notes: '' },
      { stockNo: 'CD-1010', certificate: 'GIA 9988776655', lab: 'GIA', shape: 'Heart', carat: 1.42, color: 'F', clarity: 'SI1', cut: 'Very Good', polish: 'Very Good', symmetry: 'Good', fluorescence: 'None', intensity: 'None', modifier: '', measurements: '7.5 x 7.35 x 4.1', depth: 58.4, table: 60, price: 7850, pricePerCarat: 5528, status: 'On Memo', location: 'Memo-0052', notes: 'Out to D. Fernandes' },
      { stockNo: 'CD-1011', certificate: 'GIA 1122334455', lab: 'GIA', shape: 'Marquise', carat: 1.68, color: 'H', clarity: 'VS1', cut: 'Excellent', polish: 'Excellent', symmetry: 'Excellent', fluorescence: 'Faint', intensity: 'None', modifier: '', measurements: '11.2 x 5.9 x 3.55', depth: 61.0, table: 58, price: 9300, pricePerCarat: 5536, status: 'Available', location: 'Vault B-04', notes: '' },
      { stockNo: 'CD-1012', certificate: 'IGI 5566778899', lab: 'IGI', shape: 'Oval', carat: 2.55, color: 'G', clarity: 'VVS2', cut: 'Excellent', polish: 'Excellent', symmetry: 'Excellent', fluorescence: 'None', intensity: 'None', modifier: '', measurements: '10.1 x 7.2 x 4.5', depth: 61.5, table: 57, price: 28900, pricePerCarat: 11333, status: 'Available', location: 'Vault C-01', notes: '' },
      { stockNo: 'CD-1013', certificate: 'GIA 4433221100', lab: 'GIA', shape: 'Round', carat: 0.75, color: 'J', clarity: 'SI1', cut: 'Good', polish: 'Very Good', symmetry: 'Good', fluorescence: 'Medium', intensity: 'None', modifier: '', measurements: '5.85 x 5.82 x 3.6', depth: 61.9, table: 58, price: 2150, pricePerCarat: 2867, status: 'Available', location: 'Vault C-02', notes: '' },
      { stockNo: 'CD-1014', certificate: 'GIA 7001122334', lab: 'GIA', shape: 'Round', carat: 1.01, color: 'N', clarity: 'VS2', cut: 'Very Good', polish: 'Very Good', symmetry: 'Very Good', fluorescence: 'None', intensity: 'Fancy', modifier: 'Yellow', measurements: '6.38 x 6.35 x 3.9', depth: 61.3, table: 58, price: 12400, pricePerCarat: 12277, status: 'Available', location: 'Vault C-03', notes: 'Fancy yellow - natural.' },
      { stockNo: 'CD-1015', certificate: 'GIA 6123450987', lab: 'GIA', shape: 'Cushion', carat: 2.12, color: 'P', clarity: 'VS1', cut: 'Very Good', polish: 'Excellent', symmetry: 'Very Good', fluorescence: 'None', intensity: 'Fancy Intense', modifier: 'Pink', measurements: '7.6 x 7.1 x 4.8', depth: 65.1, table: 63, price: 68500, pricePerCarat: 32311, status: 'Available', location: 'Vault C-04', notes: 'Fancy intense pink - investment grade.' },
      { stockNo: 'CD-1016', certificate: 'GIA 9001122334', lab: 'GIA', shape: 'Pear', carat: 1.35, color: 'B', clarity: 'VS2', cut: 'Excellent', polish: 'Very Good', symmetry: 'Excellent', fluorescence: 'Faint', intensity: 'Fancy Light', modifier: 'Blue', measurements: '9.3 x 6.1 x 3.8', depth: 61.1, table: 56, price: 18900, pricePerCarat: 14000, status: 'Available', location: 'Vault C-05', notes: 'Rare fancy light blue.' },
      { stockNo: 'CD-1017', certificate: 'GIA 3110099887', lab: 'GIA', shape: 'Round', carat: 1.9, color: 'F', clarity: 'VVS2', cut: 'Excellent', polish: 'Excellent', symmetry: 'Excellent', fluorescence: 'None', intensity: 'None', modifier: '', measurements: '7.95 x 7.9 x 4.85', depth: 61.2, table: 57, price: 22800, pricePerCarat: 12000, status: 'Returned', location: 'Vault A-05', notes: 'Returned from R. Malhotra after inspection.' },
      { stockNo: 'CD-1018', certificate: 'IGI 1223344556', lab: 'IGI', shape: 'Asscher', carat: 1.78, color: 'H', clarity: 'VS1', cut: 'Very Good', polish: 'Very Good', symmetry: 'Very Good', fluorescence: 'None', intensity: 'None', modifier: '', measurements: '6.95 x 6.9 x 4.85', depth: 66.0, table: 64, price: 10450, pricePerCarat: 5871, status: 'Available', location: 'Vault C-06', notes: '' },
    ],
  },
  {
    key: 'products',
    name: 'Products',
    icon: 'package',
    group: 'Inventory',
    description: 'Finished jewellery pieces, settings, chains and consumables.',
    fields: [
      F('sku', 'SKU', 'text', { required: true, searchable: true }),
      F('name', 'Name', 'text', { required: true, searchable: true }),
      F('category', 'Category', 'select', { options: ['Ring', 'Necklace', 'Earrings', 'Bracelet', 'Pendant', 'Chain', 'Setting', 'Loose Stone', 'Consumable'] }),
      F('metal', 'Metal', 'select', { options: ['Gold 18K', 'Gold 14K', 'Platinum', 'Silver', 'Mixed', 'N/A'] }),
      F('cost', 'Cost', 'number', { step: '0.01' }),
      F('price', 'Retail Price', 'number', { step: '0.01' }),
      F('unit', 'Unit', 'select', { options: ['pc', 'gm', 'pair', 'set'] }),
      F('minStock', 'Min Stock', 'number', { step: '1' }),
      F('status', 'Status', 'select', { options: ['Active', 'Draft', 'Discontinued'] }),
    ],
    seed: [
      { sku: 'PR-0001', name: 'Solitaire Engagement Ring 1.5ct F/VVS1', category: 'Ring', metal: 'Gold 18K', cost: 9100, price: 13900, unit: 'pc', minStock: 3, status: 'Active' },
      { sku: 'PR-0002', name: 'Halo Diamond Stud Earrings', category: 'Earrings', metal: 'Platinum', cost: 3400, price: 5400, unit: 'pair', minStock: 5, status: 'Active' },
      { sku: 'PR-0003', name: 'Cushion Cut Pendant - Fancy Yellow', category: 'Pendant', metal: 'Gold 18K', cost: 6800, price: 9800, unit: 'pc', minStock: 2, status: 'Active' },
      { sku: 'PR-0004', name: 'Tennis Bracelet - 2ct TW', category: 'Bracelet', metal: 'Gold 18K', cost: 7400, price: 11200, unit: 'pc', minStock: 2, status: 'Active' },
      { sku: 'PR-0005', name: 'Diamond Eternity Band', category: 'Ring', metal: 'Platinum', cost: 2800, price: 4600, unit: 'pc', minStock: 4, status: 'Active' },
      { sku: 'PR-0006', name: 'Gold Chain 18" - 2.2mm', category: 'Chain', metal: 'Gold 18K', cost: 420, price: 780, unit: 'gm', minStock: 10, status: 'Active' },
      { sku: 'PR-0007', name: 'Six Prong Basket Setting', category: 'Setting', metal: 'Platinum', cost: 310, price: 560, unit: 'pc', minStock: 8, status: 'Active' },
      { sku: 'PR-0008', name: 'Princess Cut Studs 0.5ct TW', category: 'Earrings', metal: 'Gold 14K', cost: 1650, price: 2650, unit: 'pair', minStock: 5, status: 'Active' },
      { sku: 'PR-0009', name: 'Pear Shaped Drop Necklace', category: 'Necklace', metal: 'Gold 18K', cost: 5100, price: 7900, unit: 'pc', minStock: 2, status: 'Active' },
      { sku: 'PR-0010', name: 'Diamond Stud Bracelet - 1ct TW', category: 'Bracelet', metal: 'Gold 18K', cost: 3900, price: 6100, unit: 'pc', minStock: 3, status: 'Draft' },
      { sku: 'PR-0011', name: 'Cushion Halo Pendant - Blue', category: 'Pendant', metal: 'Platinum', cost: 9200, price: 14800, unit: 'pc', minStock: 1, status: 'Active' },
      { sku: 'PR-0012', name: 'Pearl & Diamond Stud Set', category: 'Earrings', metal: 'Gold 14K', cost: 890, price: 1490, unit: 'pair', minStock: 6, status: 'Discontinued' },
    ],
  },
  {
    key: 'stock',
    name: 'Stock Movements',
    icon: 'warehouse',
    group: 'Inventory',
    description: 'Inbound, outbound, transfer and adjustment ledger for all items.',
    fields: [
      F('date', 'Date', 'date'),
      F('type', 'Type', 'select', { options: ['Stock In', 'Stock Out', 'Transfer', 'Adjustment', 'Return In', 'Damaged'] }),
      F('item', 'Item', 'text', { searchable: true, required: true }),
      F('reference', 'Reference', 'text', { searchable: true, placeholder: 'PO-1042 / M-0041' }),
      F('quantity', 'Quantity', 'number', { step: '1' }),
      F('unitCost', 'Unit Cost', 'number', { step: '0.01' }),
      F('totalValue', 'Total Value', 'number', { step: '0.01' }),
      F('location', 'Location', 'text', { placeholder: 'Vault A-01' }),
      F('party', 'Party', 'text'),
      F('note', 'Note', 'textarea'),
    ],
    seed: [
      { date: '2026-07-02', type: 'Stock In', item: 'CD-1001', reference: 'PO-1040', quantity: 1, unitCost: 14500, totalValue: 14500, location: 'Vault A-01', party: 'Antwerp Rough Ltd', note: 'Purchased at auction.' },
      { date: '2026-07-03', type: 'Stock In', item: 'CD-1002', reference: 'PO-1041', quantity: 1, unitCost: 18300, totalValue: 18300, location: 'Vault A-02', party: 'Shri Gems', note: '' },
      { date: '2026-07-05', type: 'Transfer', item: 'PR-0006', reference: 'TR-2210', quantity: 20, unitCost: 420, totalValue: 8400, location: 'Showroom Floor', party: '', note: 'Moved to floor stock.' },
      { date: '2026-07-07', type: 'Stock In', item: 'PR-0007', reference: 'PO-1042', quantity: 12, unitCost: 310, totalValue: 3720, location: 'Workshop', party: 'Castwell Metals', note: '' },
      { date: '2026-07-08', type: 'Stock Out', item: 'CD-1008', reference: 'INV-3021', quantity: 1, unitCost: 4613, totalValue: 4613, location: 'Sold', party: 'Elegant Jewels', note: 'Sold - invoice 3021.' },
      { date: '2026-07-10', type: 'Adjustment', item: 'CD-1006', reference: 'ADJ-004', quantity: 1, unitCost: 6556, totalValue: 6556, location: 'Vault B-01', party: '', note: 'Recount matched.' },
      { date: '2026-07-12', type: 'Stock In', item: 'CD-1012', reference: 'PO-1043', quantity: 1, unitCost: 24300, totalValue: 24300, location: 'Vault C-01', party: 'Global Diam BV', note: 'HTHP certified.' },
      { date: '2026-07-14', type: 'Stock Out', item: 'PR-0001', reference: 'INV-3024', quantity: 1, unitCost: 9100, totalValue: 9100, location: 'Sold', party: 'A. Kapoor', note: '' },
      { date: '2026-07-16', type: 'Return In', item: 'CD-1017', reference: 'RET-0088', quantity: 1, unitCost: 12000, totalValue: 12000, location: 'Vault A-05', party: 'R. Malhotra', note: 'Customer returned after inspection.' },
      { date: '2026-07-18', type: 'Stock In', item: 'CD-1015', reference: 'PO-1044', quantity: 1, unitCost: 58900, totalValue: 58900, location: 'Vault C-04', party: 'Rare Colour Co', note: 'Fancy intense pink.' },
      { date: '2026-07-20', type: 'Damaged', item: 'PR-0012', reference: 'ADJ-005', quantity: -2, unitCost: 890, totalValue: -1780, location: 'Workshop', party: '', note: 'Prongs damaged in polishing.' },
      { date: '2026-07-22', type: 'Stock In', item: 'CD-1016', reference: 'PO-1045', quantity: 1, unitCost: 15800, totalValue: 15800, location: 'Vault C-05', party: 'Blue Ice Diamonds', note: '' },
      { date: '2026-07-24', type: 'Transfer', item: 'PR-0004', reference: 'TR-2211', quantity: 1, unitCost: 7400, totalValue: 7400, location: 'Showroom Floor', party: '', note: '' },
      { date: '2026-07-26', type: 'Stock Out', item: 'PR-0003', reference: 'INV-3030', quantity: 1, unitCost: 6800, totalValue: 6800, location: 'Sold', party: 'D. Fernandes', note: '' },
      { date: '2026-07-28', type: 'Stock In', item: 'CD-1009', reference: 'PO-1046', quantity: 1, unitCost: 9600, totalValue: 9600, location: 'Vault B-03', party: 'Antwerp Rough Ltd', note: '' },
    ],
  },
  {
    key: 'memos',
    name: 'Memos',
    icon: 'file-text',
    group: 'Sales',
    description: 'Consignment memos - diamonds & jewellery sent out to customers.',
    fields: [
      F('memoNo', 'Memo No', 'text', { required: true, searchable: true }),
      F('customer', 'Customer', 'text', { required: true, searchable: true }),
      F('diamondRef', 'Item Reference', 'text', { searchable: true }),
      F('issueDate', 'Issue Date', 'date'),
      F('dueDate', 'Due Date', 'date'),
      F('status', 'Status', 'select', { options: ['Outstanding', 'Pending', 'Returned', 'Converted'] }),
      F('value', 'Memo Value', 'number', { step: '0.01' }),
      F('notes', 'Notes', 'textarea'),
    ],
    seed: [
      { memoNo: 'M-0041', customer: 'R. Mehta', diamondRef: 'CD-1003', issueDate: '2026-07-01', dueDate: '2026-07-21', status: 'Outstanding', value: 11800, notes: 'Showing to retail client.' },
      { memoNo: 'M-0042', customer: 'A. Kapoor', diamondRef: 'PR-0009', issueDate: '2026-07-03', dueDate: '2026-07-17', status: 'Converted', value: 8800, notes: 'Converted to sale INV-3022.' },
      { memoNo: 'M-0043', customer: 'Luxury Lines', diamondRef: 'CD-1005', issueDate: '2026-07-04', dueDate: '2026-07-19', status: 'Outstanding', value: 29800, notes: '' },
      { memoNo: 'M-0044', customer: 'D. Fernandes', diamondRef: 'PR-0005', issueDate: '2026-07-06', dueDate: '2026-07-20', status: 'Pending', value: 4600, notes: 'Awaiting final approval.' },
      { memoNo: 'M-0045', customer: 'S. Nair', diamondRef: 'CD-1010', issueDate: '2026-07-08', dueDate: '2026-07-22', status: 'Outstanding', value: 9400, notes: '' },
      { memoNo: 'M-0046', customer: 'Elegant Jewels', diamondRef: 'CD-1008', issueDate: '2026-07-02', dueDate: '2026-07-12', status: 'Returned', value: 5600, notes: 'Returned, no deal.' },
      { memoNo: 'M-0047', customer: 'R. Malhotra', diamondRef: 'CD-1017', issueDate: '2026-07-09', dueDate: '2026-07-16', status: 'Returned', value: 24000, notes: 'Returned after inspection.' },
      { memoNo: 'M-0048', customer: 'Blue Nile Partner', diamondRef: 'CD-1002', issueDate: '2026-07-10', dueDate: '2026-07-25', status: 'Outstanding', value: 24000, notes: '' },
      { memoNo: 'M-0049', customer: 'A. Kapoor', diamondRef: 'CD-1005', issueDate: '2026-07-12', dueDate: '2026-07-26', status: 'Outstanding', value: 26300, notes: '' },
      { memoNo: 'M-0052', customer: 'D. Fernandes', diamondRef: 'CD-1010', issueDate: '2026-07-15', dueDate: '2026-07-29', status: 'Outstanding', value: 7850, notes: '' },
    ],
  },
  {
    key: 'returns',
    name: 'Returns',
    icon: 'rotate-ccw',
    group: 'Sales',
    description: 'Customer returns, exchange requests and restocking.',
    fields: [
      F('returnNo', 'Return No', 'text', { required: true, searchable: true }),
      F('customer', 'Customer', 'text', { required: true, searchable: true }),
      F('diamondRef', 'Item Reference', 'text', { searchable: true }),
      F('date', 'Return Date', 'date'),
      F('reason', 'Reason', 'select', { options: ['Changed Mind', 'Defective', 'Wrong Size', 'Damage', 'Trade In', 'Other'] }),
      F('condition', 'Condition', 'select', { options: ['Mint', 'Good', 'Scratched', 'Damaged', 'Needs Repair'] }),
      F('status', 'Status', 'select', { options: ['Received', 'Inspected', 'Repaired', 'Restocked', 'Refunded', 'Exchanged', 'Closed'] }),
      F('amount', 'Return Value', 'number', { step: '0.01' }),
      F('notes', 'Notes', 'textarea'),
    ],
    seed: [
      { returnNo: 'RET-0085', customer: 'S. Nair', diamondRef: 'PR-0008', date: '2026-07-04', reason: 'Changed Mind', condition: 'Mint', status: 'Restocked', amount: 2650, notes: '' },
      { returnNo: 'RET-0086', customer: 'Luxury Lines', diamondRef: 'PR-0004', date: '2026-07-06', reason: 'Wrong Size', condition: 'Good', status: 'Received', amount: 11200, notes: 'Awaiting inspection.' },
      { returnNo: 'RET-0087', customer: 'Elegant Jewels', diamondRef: 'PR-0002', date: '2026-07-09', reason: 'Defective', condition: 'Needs Repair', status: 'Repaired', amount: 5400, notes: 'Replaced prong.' },
      { returnNo: 'RET-0088', customer: 'R. Malhotra', diamondRef: 'CD-1017', date: '2026-07-14', reason: 'Trade In', condition: 'Good', status: 'Restocked', amount: 24000, notes: 'Credited towards new purchase.' },
      { returnNo: 'RET-0089', customer: 'A. Kapoor', diamondRef: 'PR-0001', date: '2026-07-16', reason: 'Damage', condition: 'Damaged', status: 'Refunded', amount: 13900, notes: 'Full refund issued.' },
      { returnNo: 'RET-0090', customer: 'D. Fernandes', diamondRef: 'PR-0006', date: '2026-07-19', reason: 'Changed Mind', condition: 'Mint', status: 'Closed', amount: 780, notes: 'Accepted exchange instead.' },
      { returnNo: 'RET-0091', customer: 'Blue Nile Partner', diamondRef: 'CD-1012', date: '2026-07-22', reason: 'Other', condition: 'Good', status: 'Inspected', amount: 28900, notes: '' },
      { returnNo: 'RET-0092', customer: 'S. Nair', diamondRef: 'PR-0011', date: '2026-07-25', reason: 'Defective', condition: 'Needs Repair', status: 'Received', amount: 14800, notes: '' },
    ],
  },
  {
    key: 'expenses',
    name: 'Expenses',
    icon: 'receipt',
    group: 'Finance',
    description: 'Operating expenses, vendor payments and petty cash.',
    fields: [
      F('date', 'Date', 'date'),
      F('category', 'Category', 'select', { options: ['Rent', 'Salaries', 'Marketing', 'Travel', 'Insurance', 'Utilities', 'Consumables', 'Professional Fees', 'Other'] }),
      F('vendor', 'Vendor / Payee', 'text', { searchable: true }),
      F('amount', 'Amount', 'number', { step: '0.01', required: true }),
      F('paymentMethod', 'Payment Method', 'select', { options: ['Bank Transfer', 'Credit Card', 'Cash', 'Cheque', 'UPI'] }),
      F('paidBy', 'Paid By', 'text'),
      F('note', 'Note', 'textarea'),
    ],
    seed: [
      { date: '2026-07-02', category: 'Rent', vendor: 'Regal Towers', amount: 4200, paymentMethod: 'Bank Transfer', paidBy: 'Accounts', note: 'July showroom rent.' },
      { date: '2026-07-03', category: 'Salaries', vendor: 'Staff Payroll', amount: 18500, paymentMethod: 'Bank Transfer', paidBy: 'Accounts', note: 'July payroll.' },
      { date: '2026-07-04', category: 'Marketing', vendor: 'Vogue Ad Agency', amount: 2400, paymentMethod: 'Credit Card', paidBy: 'Marketing', note: 'Print campaign.' },
      { date: '2026-07-06', category: 'Insurance', vendor: 'Lloyd Insurance', amount: 3200, paymentMethod: 'Bank Transfer', paidBy: 'Accounts', note: 'Vault contents policy.' },
      { date: '2026-07-08', category: 'Travel', vendor: 'Emirates', amount: 890, paymentMethod: 'Credit Card', paidBy: 'Sales', note: 'Antwerp buying trip.' },
      { date: '2026-07-10', category: 'Utilities', vendor: 'City Power', amount: 540, paymentMethod: 'UPI', paidBy: 'Admin', note: '' },
      { date: '2026-07-12', category: 'Consumables', vendor: 'Castwell Metals', amount: 1120, paymentMethod: 'Bank Transfer', paidBy: 'Workshop', note: 'Gold granules.' },
      { date: '2026-07-15', category: 'Professional Fees', vendor: 'Chartered Associates', amount: 1750, paymentMethod: 'Bank Transfer', paidBy: 'Accounts', note: 'Audit fees.' },
      { date: '2026-07-17', category: 'Marketing', vendor: 'Instagram Ads', amount: 980, paymentMethod: 'Credit Card', paidBy: 'Marketing', note: 'Retargeting.' },
      { date: '2026-07-19', category: 'Travel', vendor: 'Marriott', amount: 640, paymentMethod: 'Credit Card', paidBy: 'Sales', note: '' },
      { date: '2026-07-21', category: 'Utilities', vendor: 'City Water & Gas', amount: 320, paymentMethod: 'UPI', paidBy: 'Admin', note: '' },
      { date: '2026-07-23', category: 'Salaries', vendor: 'Contract Gemologist', amount: 1400, paymentMethod: 'Bank Transfer', paidBy: 'Accounts', note: 'Part-time consultant.' },
      { date: '2026-07-25', category: 'Consumables', vendor: 'Gemlab Tools', amount: 760, paymentMethod: 'Credit Card', paidBy: 'Workshop', note: 'Polishing compounds.' },
      { date: '2026-07-27', category: 'Other', vendor: 'Trade Association', amount: 450, paymentMethod: 'Cheque', paidBy: 'Accounts', note: 'Membership renewal.' },
    ],
  },
  {
    key: 'accounts',
    name: 'Accounts',
    icon: 'book-open',
    group: 'Finance',
    description: 'Receivables, payables, payments and receipts ledger.',
    fields: [
      F('date', 'Date', 'date'),
      F('type', 'Type', 'select', { options: ['Receivable', 'Payable', 'Payment', 'Receipt'] }),
      F('party', 'Party', 'text', { searchable: true, required: true }),
      F('reference', 'Reference', 'text', { searchable: true }),
      F('amount', 'Amount', 'number', { step: '0.01', required: true }),
      F('status', 'Status', 'select', { options: ['Open', 'Partial', 'Settled', 'Overdue'] }),
      F('dueDate', 'Due Date', 'date'),
      F('note', 'Note', 'textarea'),
    ],
    seed: [
      { date: '2026-06-28', type: 'Receivable', party: 'Luxury Lines', reference: 'INV-3009', amount: 29800, status: 'Overdue', dueDate: '2026-07-12', note: 'Followed up twice.' },
      { date: '2026-07-01', type: 'Receivable', party: 'R. Mehta', reference: 'INV-3011', amount: 11800, status: 'Open', dueDate: '2026-07-30', note: '' },
      { date: '2026-07-02', type: 'Payable', party: 'Antwerp Rough Ltd', reference: 'PO-1040', amount: 14500, status: 'Open', dueDate: '2026-07-25', note: '' },
      { date: '2026-07-04', type: 'Receipt', party: 'Elegant Jewels', reference: 'INV-3021', amount: 5120, status: 'Settled', dueDate: '', note: 'Cleared via wire.' },
      { date: '2026-07-05', type: 'Receivable', party: 'A. Kapoor', reference: 'INV-3022', amount: 8800, status: 'Partial', dueDate: '2026-07-31', note: 'Paid half, balance next week.' },
      { date: '2026-07-06', type: 'Payable', party: 'Shri Gems', reference: 'PO-1041', amount: 18300, status: 'Open', dueDate: '2026-07-28', note: '' },
      { date: '2026-07-08', type: 'Receipt', party: 'S. Nair', reference: 'RET-0085', amount: -2650, status: 'Settled', dueDate: '', note: 'Restock refund processed.' },
      { date: '2026-07-10', type: 'Payable', party: 'Castwell Metals', reference: 'PO-1042', amount: 3720, status: 'Settled', dueDate: '2026-07-18', note: 'Paid in full.' },
      { date: '2026-07-12', type: 'Receivable', party: 'R. Malhotra', reference: 'INV-3026', amount: 68500, status: 'Open', dueDate: '2026-08-10', note: 'Fancy pink sale.' },
      { date: '2026-07-15', type: 'Payment', party: 'Regal Towers', reference: 'EXP-0715', amount: -4200, status: 'Settled', dueDate: '', note: 'Rent.' },
      { date: '2026-07-17', type: 'Payable', party: 'Rare Colour Co', reference: 'PO-1044', amount: 58900, status: 'Open', dueDate: '2026-08-05', note: 'Fancy pink.' },
      { date: '2026-07-19', type: 'Receivable', party: 'D. Fernandes', reference: 'INV-3030', amount: 9800, status: 'Open', dueDate: '2026-08-02', note: '' },
      { date: '2026-07-22', type: 'Receipt', party: 'Luxury Lines', reference: 'INV-3009', amount: 15000, status: 'Partial', dueDate: '', note: 'Partial payment on overdue.' },
      { date: '2026-07-24', type: 'Payable', party: 'Global Diam BV', reference: 'PO-1043', amount: 24300, status: 'Partial', dueDate: '2026-08-01', note: 'Half paid, rest on shipment.' },
      { date: '2026-07-26', type: 'Receivable', party: 'Blue Nile Partner', reference: 'INV-3031', amount: 24000, status: 'Open', dueDate: '2026-08-15', note: '' },
    ],
  },
  {
    key: 'tasks',
    name: 'Tasks',
    icon: 'list-checks',
    group: 'Operations',
    description: 'Internal to-dos, follow-ups and assignments.',
    fields: [
      F('title', 'Title', 'text', { required: true, searchable: true }),
      F('assignee', 'Assignee', 'text', { searchable: true }),
      F('dueDate', 'Due Date', 'date'),
      F('priority', 'Priority', 'select', { options: ['Low', 'Medium', 'High', 'Urgent'] }),
      F('status', 'Status', 'select', { options: ['To Do', 'In Progress', 'Review', 'Done'] }),
      F('category', 'Category', 'select', { options: ['Sales', 'Finance', 'Workshop', 'Inventory', 'Marketing', 'Admin'] }),
      F('description', 'Description', 'textarea'),
    ],
    seed: [
      { title: 'Follow up with Luxury Lines on overdue invoice', assignee: 'Sales Team', dueDate: '2026-07-30', priority: 'High', status: 'In Progress', category: 'Sales', description: 'INV-3009 is 18 days overdue.' },
      { title: 'Order replacement display trays', assignee: 'Showroom', dueDate: '2026-08-02', priority: 'Low', status: 'To Do', category: 'Admin', description: '' },
      { title: 'Appraise returned pear diamond CD-1017', assignee: 'R. Iyer', dueDate: '2026-07-29', priority: 'Medium', status: 'In Progress', category: 'Inventory', description: 'Check for wear before restock.' },
      { title: 'Renew vault insurance policy', assignee: 'Accounts', dueDate: '2026-08-05', priority: 'Urgent', status: 'To Do', category: 'Finance', description: 'Policy lapses on 08-Aug.' },
      { title: 'Prepare August catalogue photography', assignee: 'Marketing', dueDate: '2026-08-08', priority: 'Medium', status: 'Review', category: 'Marketing', description: '12 pieces queued in Media.' },
      { title: 'Polish & prong check on eternity bands', assignee: 'Workshop', dueDate: '2026-07-31', priority: 'High', status: 'In Progress', category: 'Workshop', description: '' },
      { title: 'Reconcile July bank statement', assignee: 'Accounts', dueDate: '2026-08-03', priority: 'High', status: 'To Do', category: 'Finance', description: '' },
      { title: 'Update pricing sheet for fancy colours', assignee: 'Sales Team', dueDate: '2026-08-06', priority: 'Medium', status: 'To Do', category: 'Sales', description: 'Market comps attached.' },
      { title: 'Draft memo terms for new partner', assignee: 'Legal', dueDate: '2026-08-10', priority: 'Low', status: 'To Do', category: 'Admin', description: '' },
      { title: 'Verify lab certs for incoming parcels', assignee: 'R. Iyer', dueDate: '2026-07-28', priority: 'High', status: 'Done', category: 'Inventory', description: 'PO-1045 & PO-1046 cleared.' },
      { title: 'Backup catalogue database', assignee: 'IT', dueDate: '2026-08-01', priority: 'Medium', status: 'Done', category: 'Admin', description: '' },
      { title: 'Follow up quote with Blue Nile Partner', assignee: 'Sales Team', dueDate: '2026-07-27', priority: 'High', status: 'In Progress', category: 'Sales', description: 'Quoted on CD-1012.' },
    ],
  },
  {
    key: 'messages',
    name: 'Messages',
    icon: 'mail',
    group: 'Operations',
    description: 'Customer, supplier and internal correspondence.',
    fields: [
      F('from', 'From', 'text', { searchable: true, required: true }),
      F('to', 'To', 'text', { searchable: true, required: true }),
      F('subject', 'Subject', 'text', { searchable: true }),
      F('body', 'Body', 'textarea'),
      F('type', 'Type', 'select', { options: ['Email', 'SMS', 'Internal', 'WhatsApp'] }),
      F('status', 'Status', 'select', { options: ['Unread', 'Read', 'Replied', 'Archived'] }),
      F('date', 'Date', 'date'),
      F('relatedTo', 'Related To', 'text'),
    ],
    seed: [
      { from: 'accounts@luxurylines.com', to: 'sales@colourdi.am', subject: 'Payment status INV-3009', body: 'We will wire a partial payment by Friday. Kindly confirm the bank details again.', type: 'Email', status: 'Unread', date: '2026-07-25', relatedTo: 'Luxury Lines' },
      { from: 'sales@colourdi.am', to: 'r.mehta@outlook.com', subject: 'Your memo M-0041', body: 'Just checking in on the 1.85ct cushion from memo M-0041. Should we hold it for you?', type: 'Email', status: 'Replied', date: '2026-07-24', relatedTo: 'R. Mehta' },
      { from: 'S. Nair', to: 'Showroom', subject: 'Sizing query on studs', body: 'Hi, could you confirm if the 0.5ct studs can be resized to my daughter\'s ear?', type: 'WhatsApp', status: 'Read', date: '2026-07-23', relatedTo: 'S. Nair' },
      { from: 'sales@colourdi.am', to: 'antwerprough@diamonds.be', subject: 'PO-1046 confirmation', body: 'Please confirm dispatch of CD-1009 against PO-1046. We need it before the 1st.', type: 'Email', status: 'Replied', date: '2026-07-22', relatedTo: 'Antwerp Rough Ltd' },
      { from: 'Accounts', to: 'Marketing', subject: 'Budget approval for campaign', body: 'Approved 2.4k for the August print campaign. Share the schedule.', type: 'Internal', status: 'Read', date: '2026-07-21', relatedTo: '' },
      { from: 'HR', to: 'All Staff', subject: 'Showroom maintenance this Sunday', body: 'Floor polishing scheduled Sunday 10am. Stock will be moved to vault.', type: 'Internal', status: 'Read', date: '2026-07-20', relatedTo: '' },
      { from: 'support@igiworldwide.com', to: 'sales@colourdi.am', subject: 'Certificate reprint request', body: 'We can issue a reprint for IGI 4482110033 at a nominal fee. Confirm to proceed.', type: 'Email', status: 'Unread', date: '2026-07-19', relatedTo: 'CD-1002' },
      { from: 'D. Fernandes', to: 'Sales', subject: 'Wife loved the pendant!', body: 'She loved it. Can you also show me the blue pear next week?', type: 'WhatsApp', status: 'Replied', date: '2026-07-18', relatedTo: 'D. Fernandes' },
      { from: 'Workshop', to: 'Inventory', subject: 'Damaged units moved out', body: '2 units of PR-0012 marked damaged and moved to scrap tray.', type: 'Internal', status: 'Archived', date: '2026-07-17', relatedTo: 'PR-0012' },
      { from: 'sales@colourdi.am', to: 'rarec@colourco.com', subject: 'Reference images for CD-1015', body: 'Could you send high-res videos of the fancy pink under different lights?', type: 'Email', status: 'Replied', date: '2026-07-16', relatedTo: 'CD-1015' },
      { from: 'Bank', to: 'Accounts', subject: 'Statement July available', body: 'Your July statement is available in the portal.', type: 'Email', status: 'Read', date: '2026-07-15', relatedTo: '' },
      { from: 'A. Kapoor', to: 'Sales', subject: 'Balance on INV-3022', body: 'I will pay the remaining 4.4k by month end. Holding me to it!', type: 'SMS', status: 'Read', date: '2026-07-14', relatedTo: 'A. Kapoor' },
    ],
  },
  {
    key: 'documents',
    name: 'Documents',
    icon: 'folder',
    group: 'Admin',
    description: 'Certificates, contracts, invoices and file records.',
    fields: [
      F('name', 'Name', 'text', { required: true, searchable: true }),
      F('type', 'Type', 'select', { options: ['PDF', 'Excel', 'Word', 'Image', 'Contract', 'Invoice', 'Report'] }),
      F('category', 'Category', 'select', { options: ['Certificate', 'Purchase', 'Sales', 'Contract', 'Bank', 'HR', 'Other'] }),
      F('tags', 'Tags', 'text', { placeholder: 'gia, certificate, vault' }),
      F('size', 'Size (KB)', 'number', { step: '1' }),
      F('uploadedBy', 'Uploaded By', 'text'),
      F('date', 'Date', 'date'),
      F('status', 'Status', 'select', { options: ['Current', 'Archived', 'Pending Review'] }),
    ],
    seed: [
      { name: 'GIA 2201234567 - Round 1.52ct', type: 'PDF', category: 'Certificate', tags: 'gia, cd-1001', size: 842, uploadedBy: 'R. Iyer', date: '2026-07-02', status: 'Current' },
      { name: 'IGI 4482110033 - Pear 2.04ct', type: 'PDF', category: 'Certificate', tags: 'igi, cd-1002', size: 918, uploadedBy: 'R. Iyer', date: '2026-07-03', status: 'Current' },
      { name: 'Vault Insurance Policy 2026', type: 'PDF', category: 'Contract', tags: 'insurance, vault', size: 1240, uploadedBy: 'Accounts', date: '2026-07-05', status: 'Current' },
      { name: 'PO-1040 Purchase Order', type: 'Excel', category: 'Purchase', tags: 'po, antwerp', size: 210, uploadedBy: 'Accounts', date: '2026-07-01', status: 'Current' },
      { name: 'INV-3021 Elegant Jewels', type: 'PDF', category: 'Sales', tags: 'invoice, sold', size: 164, uploadedBy: 'Sales', date: '2026-07-08', status: 'Current' },
      { name: 'Lease Agreement - Regal Towers', type: 'PDF', category: 'Contract', tags: 'lease, rent', size: 1890, uploadedBy: 'Admin', date: '2026-06-20', status: 'Current' },
      { name: 'July Bank Statement', type: 'PDF', category: 'Bank', tags: 'bank, july', size: 760, uploadedBy: 'Accounts', date: '2026-07-27', status: 'Pending Review' },
      { name: 'Staff Payroll Register July', type: 'Excel', category: 'HR', tags: 'payroll, staff', size: 312, uploadedBy: 'Accounts', date: '2026-07-03', status: 'Archived' },
      { name: 'Fancy Colour Price Sheet', type: 'Excel', category: 'Report', tags: 'pricing, fancy', size: 148, uploadedBy: 'Sales', date: '2026-07-11', status: 'Current' },
      { name: 'GIA 9001122334 - Fancy Blue Pear', type: 'PDF', category: 'Certificate', tags: 'gia, cd-1016, blue', size: 874, uploadedBy: 'R. Iyer', date: '2026-07-22', status: 'Current' },
    ],
  },
  {
    key: 'media',
    name: 'Media',
    icon: 'image',
    group: 'Admin',
    description: 'Product photography, videos, scans and marketing assets.',
    fields: [
      F('name', 'Name', 'text', { required: true, searchable: true }),
      F('type', 'Type', 'select', { options: ['Photo', 'Video', '360 Video', '3D Scan', 'Render', 'Lifestyle'] }),
      F('assetRef', 'Asset Reference', 'text', { searchable: true }),
      F('tags', 'Tags', 'text'),
      F('size', 'Size (MB)', 'number', { step: '0.1' }),
      F('uploadedBy', 'Uploaded By', 'text'),
      F('date', 'Date', 'date'),
      F('usage', 'Usage', 'select', { options: ['Catalog', 'Web', 'Instagram', 'WhatsApp', 'Print', 'Internal'] }),
    ],
    seed: [
      { name: 'CD-1001 front-lit macro', type: 'Photo', assetRef: 'CD-1001', tags: 'white, macro', size: 8.4, uploadedBy: 'Photo Studio', date: '2026-07-02', usage: 'Catalog' },
      { name: 'CD-1001 video loop', type: 'Video', assetRef: 'CD-1001', tags: 'white, video', size: 42.0, uploadedBy: 'Photo Studio', date: '2026-07-02', usage: 'Web' },
      { name: 'CD-1015 fancy pink scan', type: '3D Scan', assetRef: 'CD-1015', tags: 'pink, scan', size: 96.0, uploadedBy: 'Photo Studio', date: '2026-07-18', usage: 'Catalog' },
      { name: 'CD-1015 sparkle 360', type: '360 Video', assetRef: 'CD-1015', tags: 'pink, 360', size: 128.0, uploadedBy: 'Photo Studio', date: '2026-07-18', usage: 'Instagram' },
      { name: 'PR-0001 hero ring shot', type: 'Photo', assetRef: 'PR-0001', tags: 'ring, hero', size: 12.2, uploadedBy: 'Photo Studio', date: '2026-07-05', usage: 'Print' },
      { name: 'PR-0004 bracelet detail', type: 'Photo', assetRef: 'PR-0004', tags: 'bracelet', size: 9.8, uploadedBy: 'Photo Studio', date: '2026-07-07', usage: 'Catalog' },
      { name: 'CD-1016 blue pear render', type: 'Render', assetRef: 'CD-1016', tags: 'blue, render', size: 22.0, uploadedBy: 'Design', date: '2026-07-22', usage: 'Web' },
      { name: 'Eternity band lifestyle flatlay', type: 'Lifestyle', assetRef: 'PR-0005', tags: 'lifestyle', size: 14.6, uploadedBy: 'Photo Studio', date: '2026-07-09', usage: 'Instagram' },
      { name: 'PR-0002 studs video loop', type: 'Video', assetRef: 'PR-0002', tags: 'studs, video', size: 38.0, uploadedBy: 'Photo Studio', date: '2026-07-03', usage: 'WhatsApp' },
      { name: 'CD-1012 oval macro', type: 'Photo', assetRef: 'CD-1012', tags: 'oval, macro', size: 10.1, uploadedBy: 'Photo Studio', date: '2026-07-12', usage: 'Catalog' },
    ],
  },
  {
    key: 'integrations',
    name: 'Integrations',
    icon: 'plug',
    group: 'Admin',
    description: 'Third-party services and marketplace connections.',
    fields: [
      F('name', 'Name', 'text', { required: true, searchable: true }),
      F('provider', 'Provider', 'text', { searchable: true }),
      F('category', 'Category', 'select', { options: ['Marketplace', 'Payment', 'Shipping', 'CRM', 'Accounting', 'Email', 'Website'] }),
      F('status', 'Status', 'select', { options: ['Connected', 'Not Connected', 'Error', 'Setup Required'] }),
      F('apiKeyMasked', 'API Key (masked)', 'text', { readonly: true }),
      F('connectedAt', 'Connected At', 'date'),
      F('dataScope', 'Data Scope', 'text', { placeholder: 'Products, Orders, Inventory' }),
      F('description', 'Description', 'textarea'),
    ],
    seed: [
      { name: 'B2B Marketplace', provider: 'DiamondPort', category: 'Marketplace', status: 'Connected', apiKeyMasked: 'dp_live_••••4812', connectedAt: '2026-03-14', dataScope: 'Products, Inventory, Orders', description: 'Live product feed with automatic stock sync.' },
      { name: 'Payment Gateway', provider: 'Stripe', category: 'Payment', status: 'Connected', apiKeyMasked: 'sk_live_••••99aa', connectedAt: '2026-01-20', dataScope: 'Payments, Invoices', description: 'Cards, UPI and wire confirmations.' },
      { name: 'Courier API', provider: 'FedEx', category: 'Shipping', status: 'Connected', apiKeyMasked: 'fx_••••2201', connectedAt: '2026-04-02', dataScope: 'Shipments, Tracking', description: 'Insured international diamond shipping.' },
      { name: 'Email Marketing', provider: 'Mailchimp', category: 'Email', status: 'Connected', apiKeyMarked: '', apiKeyMasked: 'mc_••••77c3', connectedAt: '2026-02-11', dataScope: 'Audiences, Campaigns', description: 'Monthly newsletter to 4k subscribers.' },
      { name: 'Accounting Sync', provider: 'QuickBooks', category: 'Accounting', status: 'Error', apiKeyMasked: 'qb_••••0f12', connectedAt: '2026-05-30', dataScope: 'Invoices, Expenses', description: 'Token expired - reauthorise.' },
      { name: 'CRM', provider: 'HubSpot', category: 'CRM', status: 'Not Connected', apiKeyMasked: '', connectedAt: '', dataScope: 'Contacts, Deals', description: 'Planned for Q3.' },
      { name: 'Lab Certificate API', provider: 'GIA Verify', category: 'Website', status: 'Connected', apiKeyMasked: 'gia_••••5e10', connectedAt: '2026-06-18', dataScope: 'Certificate verification', description: 'Auto-verifies certs on intake.' },
      { name: 'Client Portal', provider: 'ColourDiam Cloud', category: 'Website', status: 'Setup Required', apiKeyMasked: '', connectedAt: '', dataScope: 'Inventory, Memos', description: 'White-label portal for top clients.' },
    ],
  },
  {
    key: 'workflows',
    name: 'Workflows',
    icon: 'workflow',
    group: 'Admin',
    description: 'Automated business processes and approval chains.',
    fields: [
      F('name', 'Name', 'text', { required: true, searchable: true }),
      F('entity', 'Entity', 'select', { options: ['Diamond', 'Product', 'Memo', 'Return', 'Expense', 'Account', 'Task', 'Document'] }),
      F('trigger', 'Trigger', 'select', { options: ['On Create', 'On Status Change', 'On Schedule', 'On Import', 'Manual'] }),
      F('steps', 'Steps', 'textarea', { placeholder: 'One step per line, e.g.\n1. Validate certificate\n2. Notify inventory manager' }),
      F('status', 'Status', 'select', { options: ['Active', 'Draft', 'Paused', 'Archived'] }),
      F('owner', 'Owner', 'text'),
      F('lastRun', 'Last Run', 'date'),
      F('description', 'Description', 'textarea'),
    ],
    seed: [
      { name: 'New Diamond Intake', entity: 'Diamond', trigger: 'On Create', steps: '1. Validate certificate number with lab API\n2. Check duplicate stock no\n3. Notify inventory manager\n4. Tag location', status: 'Active', owner: 'R. Iyer', lastRun: '2026-07-28', description: 'Standard verification flow for every new stone.' },
      { name: 'Memo Overdue Escalation', entity: 'Memo', trigger: 'On Status Change', steps: '1. Detect memo past due date\n2. Email customer reminder\n3. Escalate to sales manager if 7 days late', status: 'Active', owner: 'Sales Team', lastRun: '2026-07-25', description: 'Automatically chases outstanding memos.' },
      { name: 'Expense Approval (>5k)', entity: 'Expense', trigger: 'On Create', steps: '1. Auto-approve under 5k\n2. Route above 5k to accounts head\n3. Log to ledger', status: 'Active', owner: 'Accounts', lastRun: '2026-07-23', description: 'Tiered expense approval.' },
      { name: 'Return Restock Flow', entity: 'Return', trigger: 'On Status Change', steps: '1. Inspect condition\n2. Update stock movement\n3. Re-price if damaged', status: 'Active', owner: 'Workshop', lastRun: '2026-07-16', description: 'Handles returned stones end to end.' },
      { name: 'Weekly Stock Snapshot', entity: 'Product', trigger: 'On Schedule', steps: '1. Aggregate inventory value\n2. Send Friday report to management', status: 'Active', owner: 'Inventory', lastRun: '2026-07-24', description: 'Weekly valuation report.' },
      { name: 'Certificate Renewal Reminder', entity: 'Document', trigger: 'On Schedule', steps: '1. Find expiring certs\n2. Queue reprint requests\n3. Notify R. Iyer', status: 'Paused', owner: 'R. Iyer', lastRun: '2026-06-30', description: 'Paused pending lab pricing review.' },
      { name: 'Import Batch Validation', entity: 'Diamond', trigger: 'On Import', steps: '1. Parse spreadsheet\n2. Reject rows missing cert\n3. Stage for review', status: 'Draft', owner: 'Inventory', lastRun: '', description: 'Bulk upload guardrails.' },
      { name: 'Overdue Invoice Dunning', entity: 'Account', trigger: 'On Schedule', steps: '1. Find invoices past 30 days\n2. Send dunning email\n3. Flag for collections', status: 'Active', owner: 'Accounts', lastRun: '2026-07-27', description: 'Automated dunning cycle.' },
    ],
  },
  {
    key: 'roles',
    name: 'Roles & Permissions',
    icon: 'shield',
    group: 'Admin',
    description: 'Role definitions controlling module access and actions.',
    fields: [
      F('name', 'Name', 'text', { required: true, searchable: true }),
      F('permissions', 'Permissions', 'multiselect', { options: ['diamonds.view', 'diamonds.edit', 'products.view', 'products.edit', 'memos.view', 'memos.edit', 'returns.view', 'returns.edit', 'expenses.view', 'expenses.edit', 'accounts.view', 'accounts.edit', 'tasks.view', 'tasks.edit', 'messages.view', 'messages.edit', 'documents.view', 'documents.edit', 'media.view', 'media.edit', 'integrations.view', 'integrations.edit', 'workflows.view', 'workflows.edit', 'roles.view', 'roles.edit', 'reports.view', 'reports.export'] }),
      F('users', 'Users', 'text', { placeholder: 'Comma separated names' }),
      F('description', 'Description', 'textarea'),
    ],
    seed: [
      { name: 'Administrator', permissions: ['diamonds.view', 'diamonds.edit', 'products.view', 'products.edit', 'memos.view', 'memos.edit', 'returns.view', 'returns.edit', 'expenses.view', 'expenses.edit', 'accounts.view', 'accounts.edit', 'tasks.view', 'tasks.edit', 'messages.view', 'messages.edit', 'documents.view', 'documents.edit', 'media.view', 'media.edit', 'integrations.view', 'integrations.edit', 'workflows.view', 'workflows.edit', 'roles.view', 'roles.edit', 'reports.view', 'reports.export'], users: 'System Admin', description: 'Full access to every module and setting.' },
      { name: 'Sales Manager', permissions: ['diamonds.view', 'diamonds.edit', 'products.view', 'memos.view', 'memos.edit', 'returns.view', 'returns.edit', 'tasks.view', 'tasks.edit', 'messages.view', 'messages.edit', 'media.view', 'reports.view', 'reports.export'], users: 'A. Kapoor, D. Fernandes', description: 'Can sell, memo and chase clients.' },
      { name: 'Inventory Manager', permissions: ['diamonds.view', 'diamonds.edit', 'products.view', 'products.edit', 'memos.view', 'memos.edit', 'returns.view', 'workflows.view', 'media.view', 'reports.view'], users: 'R. Iyer', description: 'Controls stock and workflows.' },
      { name: 'Accounts', permissions: ['diamonds.view', 'products.view', 'expenses.view', 'expenses.edit', 'accounts.view', 'accounts.edit', 'documents.view', 'documents.edit', 'reports.view', 'reports.export'], users: 'Finance Team', description: 'Expenses, ledger and reporting only.' },
      { name: 'Viewer', permissions: ['diamonds.view', 'products.view', 'media.view', 'documents.view'], users: 'Marketing', description: 'Read-only catalogue access.' },
    ],
  },
];

export default MODULES;
