import React, { useEffect, useState } from "react";
import { useOutletContext } from "react-router-dom";
import { api } from "../api";
import { Button, Card, Field, Input, Spinner } from "../components/ui";
import type { AppContext } from "../components/Layout";

interface Meta {
  company: {
    name: string;
    website: string;
    currency: string;
    taxRate: number;
    address: string;
    phone: string;
    email: string;
  };
}

export default function Settings() {
  const { show } = useOutletContext<AppContext>();
  const [meta, setMeta] = useState<Meta | null>(null);
  const [form, setForm] = useState<Record<string, string>>({});
  const [saving, setSaving] = useState(false);
  const [resetConfirm, setResetConfirm] = useState(false);
  const me = JSON.parse(localStorage.getItem("cd_erp_user") || "null");
  const isAdmin = me?.role === "admin";

  useEffect(() => {
    api.get<Meta>("/api/meta").then((m) => {
      setMeta(m);
      setForm({
        name: m.company.name,
        website: m.company.website,
        currency: m.company.currency,
        taxRate: String(m.company.taxRate),
        address: m.company.address,
        phone: m.company.phone,
        email: m.company.email
      });
    });
  }, []);

  const save = async () => {
    setSaving(true);
    try {
      await api.post("/api/meta", { company: { ...meta?.company, ...form, taxRate: Number(form.taxRate) } });
      show("Company settings saved");
    } catch (e) {
      show(e instanceof Error ? e.message : "Save failed", "err");
    } finally {
      setSaving(false);
    }
  };

  const resetDemo = async () => {
    try {
      await api.post("/api/admin/reset");
      setResetConfirm(false);
      show("Demo data reset");
      window.location.reload();
    } catch (e) {
      show(e instanceof Error ? e.message : "Reset failed", "err");
    }
  };

  if (!meta) {
    return (
      <div className="flex h-40 items-center justify-center">
        <Spinner className="h-6 w-6" />
      </div>
    );
  }

  return (
    <div className="max-w-3xl space-y-5">
      <Card className="p-6">
        <h3 className="font-display text-lg font-semibold text-ink-950">Company profile</h3>
        <p className="mt-0.5 text-xs text-ink-500">Shown on documents and reports generated by the ERP.</p>
        <div className="mt-5 grid grid-cols-1 gap-4 sm:grid-cols-2">
          <Field label="Company name" required>
            <Input value={form.name || ""} onChange={(e) => setForm({ ...form, name: e.target.value })} />
          </Field>
          <Field label="Website">
            <Input value={form.website || ""} onChange={(e) => setForm({ ...form, website: e.target.value })} />
          </Field>
          <Field label="Currency">
            <Input value={form.currency || ""} onChange={(e) => setForm({ ...form, currency: e.target.value })} />
          </Field>
          <Field label="Default tax rate (%)">
            <Input type="number" value={form.taxRate || "0"} onChange={(e) => setForm({ ...form, taxRate: e.target.value })} />
          </Field>
          <Field label="Phone">
            <Input value={form.phone || ""} onChange={(e) => setForm({ ...form, phone: e.target.value })} />
          </Field>
          <Field label="Email">
            <Input value={form.email || ""} onChange={(e) => setForm({ ...form, email: e.target.value })} />
          </Field>
          <div className="sm:col-span-2">
            <Field label="Registered address">
              <Input value={form.address || ""} onChange={(e) => setForm({ ...form, address: e.target.value })} />
            </Field>
          </div>
        </div>
        <div className="mt-5 flex justify-end">
          <Button onClick={save} disabled={saving}>{saving ? "Saving…" : "Save settings"}</Button>
        </div>
      </Card>

      <Card className="p-6">
        <h3 className="font-display text-lg font-semibold text-ink-950">Document numbering</h3>
        <p className="mt-0.5 text-xs text-ink-500">Sequences used when generating new documents. Numbers are assigned automatically.</p>
        <div className="mt-5 grid grid-cols-1 gap-4 sm:grid-cols-2">
          {[
            ["Invoices", "INV-2026-"],
            ["Sales orders", "SO-2026-"],
            ["Quotes", "QT-2026-"],
            ["Purchase orders", "PO-2026-"],
            ["Payments", "PAY-2026-"]
          ].map(([label, prefix]) => (
            <div key={label} className="flex items-center justify-between rounded-xl bg-ivory px-4 py-3">
              <span className="text-sm text-ink-700">{label}</span>
              <span className="font-mono text-sm text-ink-900">{prefix}<span className="text-ink-400">0001</span></span>
            </div>
          ))}
        </div>
      </Card>

      {isAdmin && (
        <Card className="border border-red-100 p-6">
          <h3 className="font-display text-lg font-semibold text-red-700">Danger zone</h3>
          <p className="mt-0.5 text-xs text-ink-500">Reset the ERP back to its original demonstration dataset. All changes will be lost.</p>
          <div className="mt-4">
            {resetConfirm ? (
              <div className="flex items-center gap-2">
                <Button variant="danger" onClick={resetDemo}>Confirm reset</Button>
                <Button variant="secondary" onClick={() => setResetConfirm(false)}>Cancel</Button>
              </div>
            ) : (
              <Button variant="danger" onClick={() => setResetConfirm(true)}>Reset demo data</Button>
            )}
          </div>
        </Card>
      )}

      <p className="pb-4 text-center text-xs text-ink-400">
        Colour Diam ERP · www.colourdiam.com · Built with the Colour Diam API
      </p>
    </div>
  );
}
